import sys
from cx_Freeze import setup, Executable


build_exe_options = {
    "packages": [
        "os",
        "shutil",
        "math",
        "subprocess",
        "threading",
        "ctypes",
        "tkinter",
        "just_playback",
        "pytubefix",
        "librosa",
        "pydub",
        "PIL",
        "chord_extractor",
        "datatypes", 
        "audioread",
        "decorator",
        "joblib",
        "lazy_loader",
        "msgpack",
        "numba",
        "numpy",
        "pooch",
        "scipy",
        "soundfile",
        "soxr",
        "typing_extensions",
        "certifi",
        "cffi",
        "charset_normalizer",
        "idna",
        "llvmlite",
        "packaging",
        "platformdirs",
        "pycparser",
        "requests",
        "threadpoolctl",
        "urllib3",
    ],
    "includes": [
        "tkinter",
        "tkinter.ttk",
        "tkinter.filedialog",
        "PIL.Image",
        "PIL.ImageTk",
        "PIL._tkinter_finder",
        "chord_extractor.extractors",
        "datatypes.chord",
        "just_playback",
        "pytubefix",
        "librosa",
        "pydub",
        "librosa.core",
        "librosa.display",
        "librosa.effects",
        "librosa.feature",
        "librosa.onset",
        "librosa.beat",
        "librosa.decompose", 
        "librosa.segment",
        "librosa.util",
        "scipy.fft",
        "scipy.io",
        "scipy.signal",
        "scipy.spatial",
        "scipy.stats",
    ],
    "include_files": [
        "chords_diagram",
        "datatypes",
        "images",
        "vamp"
    ],
    "excludes": [],
}

base = None
if sys.platform == "win32":
    base = "Win32GUI"

setup(
    name="ChordOPython",
    version="1.0",
    description="ChordOPython",
    options={"build_exe": build_exe_options},
    executables=[Executable("main.py", base=base)],
)
