name: Build and Release ChordOPython

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.9'

      - run: |
          unzip chords_diagram/chords.zip -d chords_diagram
          rm chords_diagram/chords.zip

      - run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install numpy cx-Freeze

      - run: |
          chmod +x ./vamp/vamp-linux
          sudo cp ./vamp/vamp-linux /usr/local/bin/vamp-linux
          echo "VAMP_PATH=$PWD/vamp/vamp-linux" >> $GITHUB_ENV

      - run: |
          pip install -r req/requirements.txt

      - run: |
          cxfreeze main.py \
            --target-dir dist/output \
            --include-files chords_diagram,datatypes,images,vamp \
            --base-name=None

      - run: zip -r ChordOPython-ubuntu.zip dist/output/*

      - uses: actions/upload-artifact@v4
        with:
          name: ChordOPython-ubuntu
          path: ChordOPython-ubuntu.zip

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.9'

      - run: choco install 7zip -y

      - run: |
          7z x "chords_diagram\chords.zip" -o"chords_diagram" -y
          del chords_diagram\chords.zip
        shell: pwsh

      - run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install numpy cx-Freeze

      - run: |
          7z x "vamp/vampy-windows.zip" -o"vamp/vamp-windows" -y
          cd vamp/vamp-windows
          pip install .
        shell: pwsh

      - run: pip install -r req/requirements.txt

      - run: |
          cxfreeze main.py `
            --target-dir dist/output `
            --include-files chords_diagram,datatypes,images,vamp `
            --base-name=None
        shell: pwsh

      - run: |
          Compress-Archive -Path .\dist\output\* -DestinationPath .\ChordOPython-windows.zip
        shell: pwsh

      - uses: actions/upload-artifact@v4
        with:
          name: ChordOPython-windows
          path: ChordOPython-windows.zip

  build-macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - run: echo "/usr/local/opt/gettext/bin" >> $GITHUB_PATH
        shell: bash

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.9'

      - run: |
          unzip chords_diagram/chords.zip -d chords_diagram
          rm chords_diagram/chords.zip

      - run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install numpy cx-Freeze

      - run: |
          hdiutil attach ./vamp/vamp-macos.dmg
          echo "VAMP_PATH=$PWD/vamp/vamp-macos.dmg" >> $GITHUB_ENV

      - run: pip install -r req/requirements.txt

      - run: |
          cxfreeze main.py \
            --target-dir dist/output \
            --include-files chords_diagram,datatypes,images,vamp \
            --base-name=None

      - run: zip -r ChordOPython-macos.zip dist/output/*

      - uses: actions/upload-artifact@v4
        with:
          name: ChordOPython-macos
          path: ChordOPython-macos.zip
